/**
 * June 2026 ship notes. Append-only within the month; one entry per
 * user-visible change, written in customer language. See ./index.ts
 * for the maintenance rule.
 */
import type { ChangelogEntry } from "./index";

export const entries: ChangelogEntry[] = [
  {
    date: "2026-06-19",
    kind: "new",
    title: "Dark mode",
    body: "DSO Hire now has a full dark mode. Use the Light / Dark / System toggle in the navigation (or your menu on mobile) — it remembers your choice and follows your device by default. It's built to our own palette, not a washed-out gray, and it loads instantly with no white flash.",
  },
  {
    date: "2026-06-16",
    kind: "new",
    title: "Every rejection now records a reason",
    body: "When you reject or close out a candidate, you now choose a standardized reason — insufficient experience, schedule mismatch, stronger candidate selected, and so on. It's required on rejections (the way the big ATSs do it), stays internal to your team (the candidate never sees the code), and flows into your CSV export so you have clean, defensible records of why each applicant wasn't selected.",
  },
  {
    date: "2026-06-16",
    kind: "new",
    title: "Stay ahead of expiring licenses and certifications",
    body: "DSO Hire now watches credential expirations for the people you're hiring or have hired. Each candidate's page gets a hire-readiness checklist once they reach offer or hired (required verifications + credential status + anything expiring), your dashboard shows a \"Credentials expiring\" roll-up, and a once-a-week email gives owners and admins a heads-up when something is expired or expiring within 30 days — the details stay behind sign-in.",
  },
  {
    date: "2026-06-16",
    kind: "improved",
    title: "Market pay now covers dental specialists and lab techs",
    body: "Our market-pay guidance expanded from 5 dental roles to 10 — adding oral & maxillofacial surgeons, orthodontists, prosthodontists, other specialists (endo/perio/pedo), and dental lab technicians, with metro-level precision. It shows up everywhere pay does: the job builder, the offer builder, and a candidate's \"Your market.\"",
  },
  {
    date: "2026-06-15",
    kind: "new",
    title: "See your locations as a grid — and filter by state",
    body: "Your Locations page now has a List ⇄ Grid toggle plus a footprint summary up top — how many offices you run across how many states — with clickable state chips that filter the whole page down to a single state. Grid view lays out each office as a card with its logo, city and state, address, and active-job count. Your view choice is remembered, and sorting works the same in both views.",
  },
  {
    date: "2026-06-15",
    kind: "new",
    title: "Ask the assistant to move, note, or assign — you click to confirm",
    body: "The support assistant can now draft three actions on an application — move it to a stage, add a private team note, or assign it to a teammate. Just ask (\"move her to interview\", \"note that she's strong on comms\", \"assign this to Dana\"). The assistant never makes the change itself: it hands you a confirm card, and your one click runs through the exact same permission checks as the buttons in the app. Anything outside those three, it'll point you to instead.",
  },
  {
    date: "2026-06-15",
    kind: "new",
    title: "The assistant can take you straight there",
    body: "Ask the assistant where something lives and it now hands you a one-click button — \"Open the pipeline board ↗\", \"Open this application's messages ↗\", \"Open the résumé builder ↗\" — instead of a written click-path. It only ever links to pages inside DSO Hire that your account can open.",
  },
  {
    date: "2026-06-15",
    kind: "improved",
    title: "Support answers now show their sources",
    body: "When the assistant answers, it now shows small \"✦ Sources\" chips beneath the reply — the help article it cited (tap to open it) and the parts of your account it looked at (your team, this application's status, your pipeline…). You can see exactly what an answer was grounded on, and help links read as clean titles instead of raw URLs.",
  },
  {
    date: "2026-06-15",
    kind: "improved",
    title: "The support assistant now knows what you're looking at",
    body: "Open the \"?\" assistant from an application, job, or pipeline and it already knows the record you're viewing — ask \"why is her fit 84?\" or \"what's the status here?\" without pasting an id or re-explaining. A small \"Viewing:\" chip in the assistant shows exactly which record it's grounded on, and it only ever picks up records your account can already see.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "⌘K search comes to the candidate side",
    body: "Press ⌘K (or Ctrl+K) anywhere in your candidate workspace to search open jobs, your own applications, and shortcuts — résumé builder, assessments, privacy settings, and more — without touching the mouse. Same fast palette employers have had; now both sides of DSO Hire share it.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Matches now lead with the why",
    body: "\"Roles that fit you\" — on your dashboard and both fit hubs — now shows why each role fits, not just the number: small chips naming the dimensions that genuinely scored strong for you (role match, schedule, compensation…). They come straight from the same engine that computed the score, with an honesty floor — a weak match gets no decorative chips.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Your applications, as journeys",
    body: "The candidate dashboard now shows each active application as a journey — the same stage stepper employers see, from Applied through Hired, with your current step marked. Each journey carries one honest status line: an offer waiting, a new message, or how fast this practice typically responds — a real median from their actual response history, shown only when there's enough of it to be honest (never a made-up reassurance). And per our long-standing rule, no \"stuck in review for 14 days\" anxiety timers — ever.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Your dashboard now suggests one thing, not a checklist",
    body: "The candidate dashboard's onboarding checklist is gone. In its place: a profile-strength ring with one suggestion at a time — the biggest unlock first, with an honest note on what it actually improves (\"location unlocks commute-distance matching,\" not vague points). Alongside it, a line of real facts from your own search: roles that fit you right now, unread replies, applications at interview or offer. Nothing gates, nothing guilts — your profile, your pace.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Structured pay is now editable — and offers check against it",
    body: "Postings with structured compensation can now be edited on the job's edit page, not just at creation — same builder, same live behavior. And the offer composer's range check learned the new models: drafting an offer against a percentage-based posting now compares your base against the posting's estimated annual range instead of silently skipping the check.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Hygienist pay, the way hygiene actually works",
    body: "Posting a hygienist role and picking the percentage path now reads \"Hourly + production %\" — because that's the deal in hygiene: an hourly base (the field hints the $42–60 market band) plus a share of hygiene production above a threshold. Same honest preview, same matching rules.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Comp defaults tuned by people who've run DSOs",
    body: "Three refinements from operator review: day-rate guarantees now default to a ramp-up window (most are — permanent stays one click away) with honest market hints in the field ($750–1,000/day for GPs, specialty-aware); draw deals read candidate-first — the percentage leads and the day rate reads as an advance while collections ramp, not payroll jargon; and configuring a permanent day-rate floor against a percentage gets a quiet gut-check note about production incentives. Plus: the Matchability meter now carries the PracticeFit wordmark — DSOFit on corporate postings — because that's whose judgment it is.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "The AI job-description writer speaks the deal too",
    body: "Draft a description for a posting with structured compensation and the AI now writes the deal the way a dental recruiter would — your exact guarantee, percentage, and basis, woven in naturally, figures used verbatim, never converted or embellished. It also stopped assuming \"contract\" means 1099 — worker classification is its own fact now, and the writer only states what you chose.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Post pay the way dentistry actually pays",
    body: "The job wizard now speaks dental compensation: straight percentage, daily guarantee plus percentage, draw against collections, or salary-versus-percentage — with the details that decide a deal: production vs. collections basis, whether hygiene exam fees count, the lab-fee policy, pay cadence, even basis exclusions. Add your good-faith estimated annual range so candidates can compare and matching can work. W-2 vs 1099 is now a posting field too. Candidates see the deal exactly as you define it — live in the preview as you build. Simple ranges still work exactly as before.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Screening questions that know the new roles",
    body: "Every new role ships with a curated screening set written in dental, not HR-speak: dental therapists get state-authorization and scope-of-practice questions, sterilization techs get equipment and spore-testing checks, lab techs get digital-workflow and remake-handling questions, coordinators get case-size, denial-appeal, and no-show-tactic questions, and practice administrators get P&L-ownership and compliance-program questions. One click adds any of them to your posting.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Post jobs for every seat in the practice",
    body: "The job wizard's role list now covers the whole practice — the seven new roles are postable with matching labels everywhere, and the public job browser filters by all of them. Regional Manager moved to the corporate wizard where multi-site leadership belongs (existing Regional Manager postings keep working and stay editable).",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "The role list finally matches a real practice",
    body: "Seven new practice-level roles across the platform: Dental Therapist, Sterilization Technician, and Dental Lab Technician on the clinical side; Treatment, Financial/Insurance, and Scheduling Coordinators plus Practice Administrator in the front office. \"Associate Dentist\" is now simply \"Dentist.\" Candidates can pick the new roles today; matching understands how they neighbor each other — a sterilization tech is one step from an assistant role, not a stranger to it. Regional Manager now lives on the DSO side, where multi-site leadership belongs.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "The corporate wizard gets the studio treatment too",
    body: "Corporate postings now build with the same live preview beside the form, plus a DSOFit Matchability meter tuned to corporate dimensions — seniority, domain, leadership scope, work mode, travel. Same idea: see what candidates will see, and know exactly which field sharpens your matches.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Start your next posting from your last one",
    body: "Most dental postings are 90% repeats of one you've already written. The new-job page now offers your recent postings as starting points — one click duplicates everything (skills and screening questions included) into a fresh draft and drops you in the editor. Or start blank, same as always.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Better postings, measurably",
    body: "Next to the job wizard's live preview there's now a Matchability meter: how many PracticeFit dimensions your posting gives the engine to work with, and exactly which field unlocks each missing one — add a pay range, name your PMS, pick the working days. It reads the same rules the matching engine runs, so what it promises is what gets scored. Practice-culture dimensions point you to your practice profile.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "See your posting form as you type it",
    body: "The job wizard now keeps a live preview beside the form on larger screens — title, pay, schedule, the opening lines of your description, and the screening-question count, rendered the way candidates will see them, updating with every keystroke. The first lines of your description are what candidates read in search results; now you're writing them with that view open.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "The board explains itself",
    body: "A new Board insights drawer on every job's pipeline: the funnel with step-by-step conversion, plus plain-English callouts computed from your own numbers — which stage is the bottleneck (median dwell vs your 90-day norm, and how many candidates there have gone quiet) and which stage is outrunning your usual pace. When there isn't enough history to say something, it says that instead.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Act on a card without opening it",
    body: "Hover any pipeline card and three quiet actions appear: jump into the conversation, open the scorecards, or advance the candidate one stage. Advancing this way behaves exactly like dragging — same confirmation, same permissions, and moving someone into Offer still takes you straight to the offer composer.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Three ways to look at your board",
    body: "New board modes, remembered between visits: Compact squeezes more cards on screen for heavy pipelines, Focus dims every column except the one you're working, and on Pipeline HQ a Lanes toggle groups each column's cards by job — so a cross-practice pipeline stops reading like one big pile. Dragging works exactly the same in every mode.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Columns that know their own pace",
    body: "Every pipeline column header now shows the median time its current candidates have been sitting there — compared against your own organization's trailing-90-day pace for that stage, not some arbitrary benchmark. Running 1.3× slower than your norm turns the header amber; 2× turns it rust. New stages without enough history stay neutral instead of guessing.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Bottlenecks you can see from across the room",
    body: "Every card on the pipeline board now carries an aging edge — its left border stays green while a candidate is moving, warms to amber after 4 days in a stage, and turns rust at 10. The days-in-stage pill follows the same clock (it used to wait until 7 and 14 days — hiring moves faster than that). A small legend above the board keeps the scale honest.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Context, right beside the conversation",
    body: "On larger screens the inbox now keeps a quiet context rail next to the thread: who you're talking to, the role and location, a pipeline journey with the real dates each stage was reached (and how long the current one has run), how fast this candidate typically replies — measured from this conversation, shown only when there's enough to measure — and a one-click jump to the full application.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "An inbox that knows whose turn it is",
    body: "Two new inbox filters: Awaiting — conversations where the candidate spoke last and the ball is in your court (stage moves don't count as replies) — and Notes, every thread your team has annotated. Rows now carry the candidate's stage and an \"Awaiting you\" chip, and when a team note is the freshest thing on a thread, the preview shows it.",
  },
  {
    date: "2026-06-12",
    kind: "new",
    title: "Type \"/\" for message templates — and notes from the composer",
    body: "The inbox composer learned two tricks. Type \"/\" to pick from ready-made replies — interview invites, screening calls, gentle nudges — with the candidate's name, the job title, and your name filled in from the conversation you're in. And a lock toggle flips the composer into internal-note mode: amber, team-only, saved straight into the timeline without ever touching the candidate.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Your team's notes, right in the conversation",
    body: "The inbox thread is now a unified timeline: messages, stage changes, and your team's internal notes interleave in one stream, in order. Notes are unmistakably amber, marked Internal, and never sent — the candidate's view is unchanged. No more flipping to the application page to remember what your team said about the conversation you're reading.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Stage moves now confirm themselves",
    body: "Move a candidate to a new stage and a quiet confirmation slides in — including when you mark someone rejected or withdrawn. Small thing, but you'll never wonder whether the click landed.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Job health you can actually read",
    body: "The job-health bars are now labeled mini-pipelines: New, Screening, Interview, and Offer counts for each opening, last 30 days. Click any strip to land on that job's board. And the application density map is gone — replaced by a ranked list of your locations by application volume, which says in one glance what the map never did.",
  },
  {
    date: "2026-06-12",
    kind: "improved",
    title: "Your dashboard greets you with what matters",
    body: "The dashboard headline now reacts to your real hiring state — a hire this week, offers awaiting answers, candidates past your response goal, a surge of applications, or a clean slate. Always true, never canned: it reads the same numbers the tiles show.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "A sharper sidebar — and it collapses",
    body: "The navigation rail got a redesign: the DSO Hire mark draws itself in on load, sections are named (Hire, Insight, Operate), the active page gets a settling green edge, and the footer tightened to one line. Best part: the tab on the rail's edge collapses it to a slim icon bar — tooltips on hover, more room for your pipeline — and it remembers your choice.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "Review candidates without leaving the keyboard",
    body: "On any application, j and k now step you through every candidate in that job's pipeline — with a position marker so you always know where you are. Open the pipeline, hit j, and review the whole stack in one sitting.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "The candidate workspace, rebuilt",
    body: "Application detail is now a true workspace: evidence organized into tabs (Profile, Screening, Messages, Offer, Internal, Timeline) beside an always-visible pipeline rail with stage, assignee, interviews, and tags. No more thirteen-section scroll — and your internal notes stay clearly walled off from anything candidate-facing.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "Job health, per opening",
    body: "Every active job on the dashboard now shows its pipeline funnel, days open, weekly application velocity, and a health dot that flags stalled candidates or overdue reviews — replacing the plain job leaderboard. The dashboard also loads with a true-to-layout skeleton, so nothing jumps when your numbers arrive.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "Your dashboard is now live",
    body: "A realtime activity rail streams new applications, candidate replies, and teammate scorecards onto your dashboard the moment they happen — no refresh, across every practice you can see.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "A leaner, faster dashboard",
    body: "The dashboard tightened up: a compact header, four at-a-glance hiring numbers with trend sparklines (awaiting review, apps this week, offers out, time-to-fill), and your action queue right below. Less scrolling, same depth.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "Time-to-fill, front and center",
    body: "The dashboard now shows your median posting-to-hire time over the trailing 90 days — the number multi-location groups actually manage to — plus a hires sparkline. Location switcher applies, like everything else.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "Your dashboard now leads with Next Best Actions",
    body: "Overdue reviews, your strongest fit, stalled candidates, and inbound interest — unified into one ranked queue at the top of the dashboard. Keyboard users: j/k to move, Enter to open.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "Help center caught up with everything new",
    body: "Seven new help articles — per-teammate permissions, confidential searches, Pipeline HQ, seat packs, the résumé builder, DSOFit, and the new apply flow — plus refreshed plan and team guides. The in-app AI assistant learned all of it too.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "The ROI calculator now counts job-board fees too",
    body: "Hiring spend is two channels, not one — agency placement fees AND per-listing job-board costs. A side-by-side spend picture shows your stack against our one flat line, and the math finally works for groups that never touch agencies.",
  },
  {
    date: "2026-06-11",
    kind: "fixed",
    title: "Pricing page polish",
    body: "The comparison header now sticks cleanly while you scroll, and the ROI calculator models large-group volumes — up to 300 locations and 600 hires a year, counted across all locations.",
  },
  {
    date: "2026-06-11",
    kind: "improved",
    title: "A pricing comparison you can actually scan",
    body: "The tier matrix is now collapsible categories with at-a-glance coverage chips — open what you care about instead of scrolling sixty rows. Roadmap items stay honestly separated from what's live.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "Walk the back office from the homepage",
    body: "A film strip of the platform's machinery — pipeline, automations, offer approvals, permissions, analytics — so you can see what's behind a posting before you sign up.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "The founder story, signed",
    body: "A real letter on /about — who built this, why, and the six things we will never do. Several of them are enforced in the database, not just promised.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "The homepage shows the live marketplace",
    body: "Real open roles, real counts, straight from the database — with honesty floors so we never inflate. What you see is what's actually hiring.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "Try PracticeFit before signing up",
    body: "A three-tap sample on the candidates page shows how fit scoring works — clearly labeled as a sample. Your real score comes from your real answers.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "ROI calculator on pricing",
    body: "Drag your locations, hires, and agency spend — see what switching saves and which tier fits. It recommends down when your footprint is small.",
  },
  {
    date: "2026-06-11",
    kind: "new",
    title: "Security, switching, and comparison pages",
    body: "An honest security posture page (including what's still on the roadmap), a white-glove switching offer, and straight category comparisons against job boards and staffing agencies.",
  },
  {
    date: "2026-06-10",
    kind: "new",
    title: "Confidential searches",
    body: "Run a sensitive replacement search only specific teammates can see. Enforced at the database layer — not just hidden in the interface.",
  },
  {
    date: "2026-06-10",
    kind: "new",
    title: "Per-teammate permissions",
    body: "30+ actions individually grantable per person on Growth and up — who can send offers, edit postings, message candidates, see billing.",
  },
  {
    date: "2026-06-10",
    kind: "new",
    title: "Seat packs",
    body: "Need a few more seats without a tier jump? +3 seats for $99/mo on Growth and Scale, prorated automatically.",
  },
  {
    date: "2026-06-10",
    kind: "new",
    title: "Free résumé builder for candidates",
    body: "Six ATS-safe templates, built from your profile in minutes, exported as clean PDF. Free forever — no watermark games.",
  },
  {
    date: "2026-06-09",
    kind: "improved",
    title: "Smarter fit scoring for corporate roles",
    body: "DSOFit now scores corporate functions on their own dimensions instead of borrowing clinical ones — scores you can take at face value.",
  },
  {
    date: "2026-06-08",
    kind: "improved",
    title: "Faster everywhere",
    body: "Dashboard loads parallelized and 49 database indexes added. The app feels noticeably snappier on big pipelines.",
  },
  {
    date: "2026-06-05",
    kind: "improved",
    title: "Rebuilt application wizard",
    body: "Applying is now one clear question at a time — with résumé autofill so candidates never type what we can read.",
  },
  {
    date: "2026-06-04",
    kind: "new",
    title: "Weekly fit digest for candidates",
    body: "A Monday email with your top new high-fit roles — only when there's something genuinely worth seeing. No matches, no email.",
  },
  {
    date: "2026-06-04",
    kind: "new",
    title: "PracticeFit assessment — ranked priorities",
    body: "Rank what matters most to you and the matching tilts accordingly. About five minutes, role-aware, and your matches explain themselves.",
  },
  {
    date: "2026-06-03",
    kind: "new",
    title: "Offer approval chains",
    body: "Offers can require owner or admin approval before anything sends — with comp guardrails and a full audit trail.",
  },
];
