/**
 * seed-demo.ts — idempotent rich demo seed for the gated DEMO project
 * (dsohire-prod / viapivvlhjqvjhoflxmp, which is becoming demo.dsohire.com).
 *
 * Run twice → identical result (wipe-by-marker then insert). This is the
 * committed source of truth for the demo data + the reset path; the founder-
 * gated /admin "Reset demo data" button calls the SAME runDemoSeed().
 *
 * Requires service-role env (NOT in .env.local — pass at run time):
 *   export NEXT_PUBLIC_SUPABASE_URL="https://viapivvlhjqvjhoflxmp.supabase.co"
 *   export SUPABASE_SERVICE_ROLE_KEY="<Project Settings → API → service_role>"
 *   npx tsx --tsconfig tsconfig.json scripts/seed-demo.ts
 *
 * Flags:
 *   --no-legacy   skip the one-time junk purge (just wipe+reseed demo_v1)
 *
 * What only this script does (vs the admin button): uploads the committed
 * headshots + generated SVG logos to the public-images bucket, and writes
 * DEMO_LOGINS.md. The DB seed itself is shared.
 */

import { createClient } from "@supabase/supabase-js";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runDemoSeed } from "../src/lib/demo-seed";
import { HEADSHOT_PERSONAS } from "../src/lib/demo-seed/data";
import { DEMO_PASSWORD, nameSlug, demoAvatarPath } from "../src/lib/demo-seed/constants";
import type { ProvisionedLogin } from "../src/lib/demo-seed/auth";

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || "";
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error(
    "Missing env. Set NEXT_PUBLIC_SUPABASE_URL (or SUPABASE_URL) and SUPABASE_SERVICE_ROLE_KEY."
  );
  process.exit(1);
}

// getPracticeFit's internal service-role client reads these names.
process.env.NEXT_PUBLIC_SUPABASE_URL = SUPABASE_URL;
process.env.SUPABASE_SERVICE_ROLE_KEY = SERVICE_KEY;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HEADSHOT_DIR = path.join(__dirname, "demo-assets", "headshots");
const REPO_ROOT = path.join(__dirname, "..");

const supa = createClient(SUPABASE_URL, SERVICE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const BUCKET = "public-images";

async function uploadHeadshots(): Promise<number> {
  let n = 0;
  for (const p of HEADSHOT_PERSONAS) {
    const file = path.join(HEADSHOT_DIR, p.file);
    if (/broken/i.test(p.file)) continue; // never upload the BROKEN file
    if (!fs.existsSync(file)) {
      console.warn(`  ! headshot missing, skipping: ${p.file}`);
      continue;
    }
    const buf = fs.readFileSync(file);
    const dest = demoAvatarPath(nameSlug(p.first, p.last));
    const contentType = p.file.endsWith(".png") ? "image/png" : "image/jpeg";
    const { error } = await supa.storage.from(BUCKET).upload(dest, buf, {
      upsert: true,
      contentType,
    });
    if (error) {
      console.warn(`  ! upload failed (${p.file}): ${error.message}`);
      continue;
    }
    n += 1;
  }
  return n;
}

function writeDemoLogins(logins: ProvisionedLogin[], heroSlug: string): void {
  const employers = logins.filter((l) => l.kind === "employer");
  const candidates = logins.filter((l) => l.kind === "candidate");
  const lines: string[] = [];
  lines.push("# DEMO_LOGINS");
  lines.push("");
  lines.push("> Auto-generated by `scripts/seed-demo.ts`. All accounts are **fictional demo data** on the gated pre-launch project. Re-running the seed (or the /admin “Reset demo data” button) keeps these credentials stable.");
  lines.push("");
  lines.push(`**Shared password (all demo logins):** \`${DEMO_PASSWORD}\``);
  lines.push("");
  lines.push("## Founder / admin");
  lines.push("- Use your existing admin account (`cameron@eslingerdental.com`) for the `/admin` command center + read-only view-as. Not recreated by the seed.");
  lines.push("");
  lines.push("## Employers (one per tier — log into the one matching the prospect's scale)");
  lines.push("");
  lines.push("| Tier / role | Name | Email |");
  lines.push("|---|---|---|");
  for (const e of employers) {
    lines.push(`| ${e.tierOrRole} | ${e.fullName} | \`${e.email}\` |`);
  }
  lines.push("");
  lines.push("## Candidates");
  lines.push("");
  lines.push("| Role in demo | Name | Email |");
  lines.push("|---|---|---|");
  for (const c of candidates) {
    lines.push(`| ${c.tierOrRole} | ${c.fullName} | \`${c.email}\` |`);
  }
  lines.push("");
  lines.push("## The two-sided demo");
  lines.push(`- **Hero DSO:** \`/${heroSlug}\` (Bridgeway Dental Partners — Scale tier).`);
  lines.push("- **Maria Lopez** is anonymous-discoverable: she shows **masked** in Bridgeway's talent pool with a rich profile + a high PracticeFit score, and there's a live double-blind prospect thread mid-conversation.");
  lines.push("- Log in as the **Bridgeway owner** to see the masked candidate → log in as **Maria** to apply/reveal → identity reveals to Bridgeway only.");
  lines.push("");
  const dest = path.join(REPO_ROOT, "DEMO_LOGINS.md");
  fs.writeFileSync(dest, lines.join("\n"));
  console.log(`Wrote ${dest}`);
}

async function main(): Promise<void> {
  const cleanupLegacy = !process.argv.includes("--no-legacy");
  console.log(`\n▶ Seeding demo data → ${SUPABASE_URL}`);
  console.log(`  legacy purge: ${cleanupLegacy ? "yes" : "no"}\n`);

  console.log("Uploading assets…");
  const heads = await uploadHeadshots();
  console.log(`  uploaded ${heads} headshots\n`);

  const result = await runDemoSeed(supa, {
    supabaseUrl: SUPABASE_URL,
    cleanupLegacy,
    log: (m) => console.log(`  ${m}`),
  });

  writeDemoLogins(result.logins, result.heroSlug);

  console.log("\n✅ Demo seed complete. Counts:");
  for (const [k, v] of Object.entries(result.counts).sort()) {
    console.log(`   ${k.padEnd(22)} ${v}`);
  }
  console.log(`\n   Two-sided pair: ${result.twoSidedPair.candidate} ↔ ${result.twoSidedPair.employerEmail}`);
  console.log(`   Hero: /${result.heroSlug}\n`);
}

main().catch((e) => {
  console.error("\n❌ Seed failed:", e);
  process.exit(1);
});
