/**
 * RAG retrieval helper for Tier 2 in-app support.
 *
 * Given a user question, returns the top-K most relevant HELP_CONTENT
 * entries by cosine similarity against pre-computed Voyage embeddings.
 * Used by /api/support/chat to build the registry slice of the system
 * prompt before calling Claude.
 *
 * Pre-computed embeddings live in src/lib/support/help-content-
 * embeddings.json — generated by scripts/generate-help-embeddings.ts.
 * If the file is missing OR stale (version hash doesn't match current
 * registry hash), retrieval falls back to returning the first K
 * entries with a console warning. This is intentional: we'd rather
 * serve mediocre support than no support at startup time when an
 * engineer forgot to re-run the embedding script.
 *
 * Cost: one Voyage API call per user question (~150 input tokens,
 * ~$0.000003 per question). Negligible.
 */

import { HELP_CONTENT, type HelpEntry } from "@/lib/help/help-content";
import { cosineSimilarity, embedTexts } from "./voyage";
import embeddingsFile from "./help-content-embeddings.json" assert { type: "json" };

interface EmbeddedEntry {
  key: string;
  text: string;
  embedding: number[];
}

interface EmbeddingFile {
  version: string;
  model: string;
  dimensions: number;
  generated_at: string;
  entries: EmbeddedEntry[];
}

const FILE = embeddingsFile as EmbeddingFile;

export interface RetrievedHelp {
  key: string;
  entry: HelpEntry;
  similarity: number;
}

/**
 * Embed the query, score against every help entry, return top-K.
 *
 * @param query     The user's support question
 * @param k         Max number of entries to return (default 5)
 * @param threshold Minimum similarity score (default 0.3) — entries
 *                  below this are dropped even if they'd be in top-K.
 *                  Tunable: 0.5 = only directly relevant, 0.3 =
 *                  topically related. Start permissive; tighten later.
 */
export async function retrieveRelevantHelp(
  query: string,
  k: number = 5,
  threshold: number = 0.3
): Promise<RetrievedHelp[]> {
  // No embeddings file yet — fall back to first K registry entries with
  // a warning. Caller still gets *some* RAG context, just unranked.
  if (!FILE.entries || FILE.entries.length === 0) {
    console.warn(
      "[rag] help-content-embeddings.json is empty — falling back to first K registry entries. " +
        "Run `npm run help-embeddings` and commit the output."
    );
    return Object.entries(HELP_CONTENT)
      .slice(0, k)
      .map(([key, entry]) => ({ key, entry, similarity: 0 }));
  }

  let queryEmbedding: number[];
  try {
    const [embedding] = await embedTexts([query], "query");
    queryEmbedding = embedding;
  } catch (err) {
    console.error("[rag] query embedding failed", err);
    // Fall back to first K — better than failing the support call entirely.
    return Object.entries(HELP_CONTENT)
      .slice(0, k)
      .map(([key, entry]) => ({ key, entry, similarity: 0 }));
  }

  // Score every entry, sort desc by similarity, threshold + take top-K.
  const scored = FILE.entries
    .map((e) => ({
      key: e.key,
      similarity: cosineSimilarity(queryEmbedding, e.embedding),
    }))
    .filter((s) => s.similarity >= threshold)
    .sort((a, b) => b.similarity - a.similarity)
    .slice(0, k);

  // Look up the full registry entry for each top hit. Drop entries
  // whose key isn't in the current registry (deleted since embedding
  // was generated — stale file).
  const result: RetrievedHelp[] = [];
  for (const s of scored) {
    const entry = HELP_CONTENT[s.key];
    if (!entry) continue;
    result.push({ key: s.key, entry, similarity: s.similarity });
  }
  return result;
}

/**
 * Format retrieved help entries as plain text suitable for inclusion
 * in the Claude system prompt. Each entry gets a labeled section so
 * Claude can cite by title in its response.
 */
export function formatHelpForPrompt(entries: RetrievedHelp[]): string {
  if (entries.length === 0) return "";
  const sections = entries.map((r) => {
    const lines: string[] = [];
    lines.push(`## ${r.entry.title}`);
    lines.push(`(Article: /help/${r.key.replace(/\./g, "-")})`);
    lines.push("");
    lines.push(r.entry.tip);
    if (r.entry.bullets && r.entry.bullets.length > 0) {
      lines.push("");
      lines.push(...r.entry.bullets.map((b) => `- ${b}`));
    }
    if (r.entry.steps && r.entry.steps.length > 0) {
      lines.push("");
      for (const step of r.entry.steps) {
        if (step.heading) lines.push(`### ${step.heading}`);
        lines.push(step.body);
        lines.push("");
      }
    }
    return lines.join("\n");
  });
  return sections.join("\n\n---\n\n");
}
