-- Employee/word-of-mouth referrals (gap N15) — 2026-06-01.
-- Capture "I know someone great" leads so they don't get lost: a teammate
-- refers from inside the app, OR anyone submits via a shareable per-DSO link.
-- Status-tracking only (submitted → hired). NO bonus/payout fields — that's
-- the practice's internal payroll matter, deliberately out of scope (same
-- reasoning as the CE/staff-roster skip).

-- Per-DSO shareable referral code (lazy-generated by the employer page).
alter table public.dsos
  add column if not exists referral_code text unique;

comment on column public.dsos.referral_code is
  'Short unique code for the public referral link /refer/<code>. Lazy-generated.';

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  dso_id uuid not null references public.dsos(id) on delete cascade,
  -- 'teammate' = submitted by a signed-in dso_user; 'link' = public link.
  source text not null check (source in ('teammate', 'link')),
  referred_by_dso_user_id uuid references public.dso_users(id) on delete set null,
  referrer_name text,
  referrer_email text,
  candidate_name text not null,
  candidate_email text,
  candidate_phone text,
  job_id uuid references public.jobs(id) on delete set null,
  note text,
  status text not null default 'submitted'
    check (status in ('submitted', 'contacted', 'interviewing', 'hired', 'closed')),
  -- Optional link to the application once the referred person applies.
  application_id uuid references public.applications(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_referrals_dso on public.referrals(dso_id, created_at desc);
create index if not exists idx_referrals_job on public.referrals(job_id) where job_id is not null;

alter table public.referrals enable row level security;

-- Same-DSO teammates can see, add, and update referrals. Public link
-- submissions are inserted by a service-role server action (which validates
-- the referral_code), so no anon policy is needed.
create policy "Referrals: read own DSO"
  on public.referrals for select
  using (dso_id = current_dso_id());

create policy "Referrals: teammate insert"
  on public.referrals for insert
  with check (dso_id = current_dso_id());

create policy "Referrals: teammate update"
  on public.referrals for update
  using (dso_id = current_dso_id())
  with check (dso_id = current_dso_id());

-- keep updated_at fresh
create or replace function public.touch_referrals_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

drop trigger if exists trg_touch_referrals on public.referrals;
create trigger trg_touch_referrals before update on public.referrals
  for each row execute function public.touch_referrals_updated_at();
